name: lint & test

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master, staging ]
jobs:
    lint-app:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 14.x
              uses: actions/setup-node@v2
              with:
                  node-version: 14.x
                  cache: 'yarn'
            - name: dependency install
              run: yarn install
            - name: ci
              run: npm ci
            - name: lint
              run: yarn run lint
            - name: tsc
              run: yarn run typescript
            - name: test
              run: yarn run test
